import image1 from "./assets/images/todo list design.jpg";
import image2 from "./assets/images/mounttech telegram miniapp.png";
import image3 from "./assets/images/expense app.png";
import image4 from "./assets/images/web 3 app.png";
import image5 from "./assets/images/picture.png";
import image6 from "./assets/images/code 2.png";
import image7 from "./assets/images/time.png";

export const PROJECTS = [
  {
    id: 1,
    type: "Conceptual Work",
    image: image3,
    about: "Expense Tracking Application",
    name: "",
    info: "An intuitive expense tracking application built with React, styled using CSS Modules, and integrated with Firebase for data management. Categorize expenses (e.g., food, transport, etc.), view monthly summaries and total expenses and user authentication and data syncing via Firebase.",
    year: 2024,
    stack: "React, Css Module, Firebase",
    role: "Front-end Developer",
    link: "https://my-expenses-eight.vercel.app/",
    git_hub_link: "https://github.com/KingsleyEffiong/MyExpense-X",
  },
  {
    id: 2,
    type: "Challenge",
    image: image2,
    about: "Telegram Mini Application",
    name: "",
    info: "SA lightweight Telegram-inspired mini application built with React, styled using Tailwind CSS, and integrated with Firebase for real-time update",
    year: 2021,
    stack: "React, Tailwind Css, Firebase",
    role: "Front-end Developer",
    link: "https://mounttechapp.vercel.app/",
    git_hub_link: "https://github.com/KingsleyEffiong/Telegram-MiniApp",
  },
  {
    id: 3,
    type: "Challenge",
    image: image4,
    about: "Decentralised Web 3 Applicaion",
    name: "",
    info: "A decentralized Web3 application built with Next.js, styled with CSS, and powered by Solidity for blockchain functionality. Smart contracts for secure and transparent transactions, Decentralized data storage and interaction with the blockchain, User-friendly interface with seamless wallet integration (e.g., MetaMask) and Real-time updates on blockchain data.",
    year: 2021,
    stack: "Next js, CSS, Solidity",
    role: "MernStack Developer",
    link: "https://token-livid.vercel.app/",
    git_hub_link: "https://github.com/KingsleyEffiong/Web-3-Web-application",
  },
  {
    id: 4,
    type: "Challenge",
    image: image5,
    about: "Document Converter",
    name: "",
    info: "This Document Converter Application is a powerful web-based tool designed to help users easily convert various document formats in a seamless and efficient manner. Built with modern web technologies such as React, Tailwind CSS, REST API, and Firebase, the application provides a smooth, intuitive, and responsive user experience.",
    year: 2025,
    stack: "React, Tailwind Css, Firebase Rest API",
    role: "Front-end Developer",
    link: "https://converter-rouge.vercel.app",
    git_hub_link: "https://github.com/KingsleyEffiong/converter-",
  },
  {
    id: 5,
    type: "Challenge",
    image: image1,
    about: "Todo list application",
    name: "",
    info: "A fully functional to-do list built with React, styled using Tailwind CSS, and powered by Firebase for real-time updates. Key Features: Add, edit, delete. User authentication with Firebase. Real-time task syncing across devices. A modern, responsive, and scalable project showcasing full-stack development skills.",
    year: 2021,
    stack: "React, Tailwind Css, Firebase",
    role: "Front-end Developer",
    link: "https://todolist-lovat-six.vercel.app/",
    git_hub_link: "https://github.com/KingsleyEffiong/Todolist",
  },
  {
    id: 6,
    type: "Challenge",
    image: image6,
    about: "CHROME URL BOOKMARKER EXTENSION",
    name: "",
    info: "The URL Bookmark Manager is a simple and efficient Chrome extension that allows users to save, view, and manage their favorite web links directly from their browser. With a clean and minimalistic UI powered by Tailwind CSS, users can quickly bookmark the current tab, view saved links, copy URLs to the clipboard, and delete unwanted bookmarks. The extension utilizes Chrome's Storage API to ensure bookmarks are synced across devices, providing a seamless and convenient browsing experience.",
    year: 2025,
    stack: "Javascript, React, Tailwind Css, Manifest json",
    role: "Front-end Developer",
    // link: "https://todolist-lovat-six.vercel.app/",
    git_hub_link: "https://github.com/KingsleyEffiong/CHROME-BOOKMARK-EXTENSION",
  },
  {
    id: 7,
    type: "Challenge",
    image: image7,
    about: "INSTAGRAM EXACT TIME VIEWER",
    name: "",
    info: "The Instagram Exact Time Viewer is a Chrome extension that lets users see the precise timestamp of Instagram posts instead of the default time hours ago format. By extracting and displaying the exact date and time of a post, this tool provides more accuracy for users who need precise posting details. With a lightweight and seamless integration, it enhances the Instagram browsing experience without affecting the platform’s UI.",
    year: 2025,
    stack: "Javascript, React, Vanilla CSS, Manifest json",
    role: "Front-end Developer",
    // link: "https://todolist-lovat-six.vercel.app/",
    git_hub_link: "https://github.com/KingsleyEffiong/instagram-time-viewer-",
  },
];
